/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AtletiRouteImport } from './routes/atleti'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ClassificheRouteImport } from './routes/classifiche'
import { Route as DocumentiRouteImport } from './routes/documenti'
import { Route as NewsRouteImport } from './routes/news'
import { Route as TitoliRouteImport } from './routes/titoli'
import { Route as AuthenticatedAreaRouteImport } from './routes/_authenticated.area'
import { Route as EventiIdRouteImport } from './routes/eventi.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletiRoute = AtletiRouteImport.update({
  id: '/atleti',
  path: '/atleti',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificheRoute = ClassificheRouteImport.update({
  id: '/classifiche',
  path: '/classifiche',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentiRoute = DocumentiRouteImport.update({
  id: '/documenti',
  path: '/documenti',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const TitoliRoute = TitoliRouteImport.update({
  id: '/titoli',
  path: '/titoli',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAreaRoute = AuthenticatedAreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EventiIdRoute = EventiIdRouteImport.update({
  id: '/eventi/$id',
  path: '/eventi/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atleti': typeof AtletiRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/classifiche': typeof ClassificheRoute
  '/documenti': typeof DocumentiRoute
  '/news': typeof NewsRoute
  '/titoli': typeof TitoliRoute
  '/area': typeof AuthenticatedAreaRoute
  '/eventi/$id': typeof EventiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atleti': typeof AtletiRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/classifiche': typeof ClassificheRoute
  '/documenti': typeof DocumentiRoute
  '/news': typeof NewsRoute
  '/titoli': typeof TitoliRoute
  '/area': typeof AuthenticatedAreaRoute
  '/eventi/$id': typeof EventiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/atleti': typeof AtletiRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/classifiche': typeof ClassificheRoute
  '/documenti': typeof DocumentiRoute
  '/news': typeof NewsRoute
  '/titoli': typeof TitoliRoute
  '/_authenticated/area': typeof AuthenticatedAreaRoute
  '/eventi/$id': typeof EventiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atleti'
    | '/auth'
    | '/calendario'
    | '/classifiche'
    | '/documenti'
    | '/news'
    | '/titoli'
    | '/area'
    | '/eventi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atleti'
    | '/auth'
    | '/calendario'
    | '/classifiche'
    | '/documenti'
    | '/news'
    | '/titoli'
    | '/area'
    | '/eventi/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/atleti'
    | '/auth'
    | '/calendario'
    | '/classifiche'
    | '/documenti'
    | '/news'
    | '/titoli'
    | '/_authenticated/area'
    | '/eventi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AtletiRoute: typeof AtletiRoute
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  ClassificheRoute: typeof ClassificheRoute
  DocumentiRoute: typeof DocumentiRoute
  NewsRoute: typeof NewsRoute
  TitoliRoute: typeof TitoliRoute
  EventiIdRoute: typeof EventiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atleti': {
      id: '/atleti'
      path: '/atleti'
      fullPath: '/atleti'
      preLoaderRoute: typeof AtletiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifiche': {
      id: '/classifiche'
      path: '/classifiche'
      fullPath: '/classifiche'
      preLoaderRoute: typeof ClassificheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documenti': {
      id: '/documenti'
      path: '/documenti'
      fullPath: '/documenti'
      preLoaderRoute: typeof DocumentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titoli': {
      id: '/titoli'
      path: '/titoli'
      fullPath: '/titoli'
      preLoaderRoute: typeof TitoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/area': {
      id: '/_authenticated/area'
      path: '/area'
      fullPath: '/area'
      preLoaderRoute: typeof AuthenticatedAreaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/eventi/$id': {
      id: '/eventi/$id'
      path: '/eventi/$id'
      fullPath: '/eventi/$id'
      preLoaderRoute: typeof EventiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAreaRoute: typeof AuthenticatedAreaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAreaRoute: AuthenticatedAreaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AtletiRoute: AtletiRoute,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  ClassificheRoute: ClassificheRoute,
  DocumentiRoute: DocumentiRoute,
  NewsRoute: NewsRoute,
  TitoliRoute: TitoliRoute,
  EventiIdRoute: EventiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
